version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
    - db:/var/lib/postgresql/data
    ports:
    - 42069:5432
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASS}

  server:
    build: server
    restart: unless-stopped
    depends_on:
    - db
    ports:
    - 127.0.0.1:8080:8080
    environment:
    - DB_HOST=db
    - DB_NAME
    - DB_USER
    - DB_PASS
    - CLIENT_ORIGIN
    - JWT_SECRET
    - ADMIN_USER
    - SMTP_HOST=smtp
    - SMTP_PORT=25
    - EMAIL_FROM
    - EMAIL_FROM_BEWERBUNG

  client:
    build:
      context: client
      args:
      - VITE_API_URL=${API_URL}
    restart: unless-stopped
    depends_on:
    - server
    ports:
    - 127.0.0.1:8081:80

  smtp:
    image: namshi/smtp
    restart: unless-stopped

volumes:
  db:
