version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
    - db:/var/lib/postgresql/data
    ports:
    - 42069:5432
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASS}

  server:
    build: server
    restart: unless-stopped
    depends_on:
    - db
    networks:
    - default
    - smtp
    - proxy
    environment:
    - DB_HOST=db
    - DB_NAME
    - DB_USER
    - DB_PASS
    - CLIENT_ORIGIN
    - JWT_SECRET
    - ADMIN_USER
    - SMTP_HOST=smtp
    - SMTP_PORT=25
    - EMAIL_FROM
    - EMAIL_FROM_BEWERBUNG
    - EMAIL_NOREPLY

  client:
    build:
      context: client
      args:
      - VITE_API_URL=${API_URL}
    restart: unless-stopped
    depends_on:
    - server
    networks:
    - proxy

volumes:
  db:

networks:
  smtp:
    external: true
  proxy:
    external: true
