version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
    - internal
    volumes:
    - db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASS}

  server:
    build: server
    restart: unless-stopped
    depends_on:
    - db
    networks:
    - internal
    - swag
    expose:
    - 8080
    environment:
    - DB_HOST=db
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}

  client:
    build:
      context: client
      args:
      - VITE_API_URL=${API_URL}
    restart: unless-stopped
    depends_on:
    - server
    networks:
    - swag
    expose:
    - 80

networks:
  internal:
  swag:
    name: swag-net
    external: true

volumes:
  db:
